name: michael-website

networks:
  proxy:
    external: true

services:
  michael-website:
    container_name: michael-website
    image: nginx:alpine
    build: .
    restart: always
    networks:
      - proxy
      - default
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
    command: /bin/sh -c "nginx -t && nginx -g 'daemon off;'"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/nginx-health']
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.michael-website.rule=Host(`michaeldistel.com`) || Host(`distel.me`)'
      - 'traefik.http.routers.michael-website.entrypoints=websecure'
      - 'traefik.http.routers.michael-website.tls=true'
      - 'traefik.http.routers.michael-website.tls.certresolver=myresolver'
      - 'traefik.http.services.michael-website.loadbalancer.server.port=80'
