name: michael-website

networks:
  proxy:
    external: true

services:
  michael-website:
    container_name: michael-website
    image: nginx:alpine
    restart: always
    networks:
      - proxy
      - default
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./build:/usr/share/nginx/html:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.michael-website.rule=Host(`michael.antonshubin.com`) || Host(`michaeldistel.com`)|| Host(`distel.me`)'
      - 'traefik.http.routers.michael-website.entrypoints=websecure'
      - 'traefik.http.routers.michael-website.tls=true'
      - 'traefik.http.routers.michael-website.tls.certresolver=myresolver'
      - 'traefik.http.services.michael-website.loadbalancer.server.port=80'
